USE TPINT_PERSONAL
GO

CREATE PROCEDURE SP_AGREGARMEDICO
AS
DECLARE @DNI NCHAR(9)
DECLARE @NOMBRE VARCHAR(50)
DECLARE @APELLIDO VARCHAR(50)
DECLARE @TIPO NCHAR(2)
DECLARE @SEXO CHAR
DECLARE @NACIONALIDAD VARCHAR(50)
DECLARE @FECHANAC DATE
DECLARE @DIRECCION VARCHAR(50)
DECLARE @IDPROVINCIA INT
DECLARE @IDLOCALIDAD INT
DECLARE @EMAIL VARCHAR(50)
DECLARE @TELEFONO VARCHAR(50)
-- LEGAJO SE CARGA SOLO
DECLARE @CODESPECIALIDAD INT
DECLARE @HORARIO VARCHAR(100)
-- ESTADO SE CARGA SOLO
DECLARE @USUARIO VARCHAR(20)
DECLARE @PASSWORD VARCHAR(20)


BEGIN

INSERT INTO USUARIOS(
	dni_U,
	nombre_U,
	apellido_U,
	tipo_U,
	sexo_U,
	nacionalidad_U,
	fechaNac_U,
	direccion_U,
	idLocalidad_U,
	idProvincia_U,
	email_U,
	telefono_U,
	codEspecialidad_U,
	horario_U,
	usuario_U,
	password_U)
VALUES (
	 @DNI,
	 @NOMBRE,
	 @APELLIDO,
	 @TIPO,
	 @SEXO,
	 @NACIONALIDAD,
	 @FECHANAC,
	 @DIRECCION,
	 @IDPROVINCIA,
	 @IDLOCALIDAD,
	 @EMAIL,
	 @TELEFONO,
	 @CODESPECIALIDAD,
	 @HORARIO,
	 @USUARIO,
	 @PASSWORD
)
END
GO
